#!/usr/bin/bash
#

source /tmp/secrets

dir=${1:-$PWD}
cd $dir

[ -z $OPENWEATHERMAP_KEY_ID ] || sed -i "s|OPENWEATHERMAP_KEY_ID=<ADD_YOUR_KEY_ID>|OPENWEATHERMAP_KEY_ID=${OPENWEATHERMAP_KEY_ID}|g" docker-compose.yml
[ -z $TWITTER_CONSUMER_KEY ] || sed -i "s|TWITTER_CONSUMER_KEY=<ADD_YOUR_CONSUMER_KEY>|TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}|g" docker-compose.yml
[ -z $TWITTER_CONSUMER_SECRET ] || sed -i "s|TWITTER_CONSUMER_SECRET=<ADD_YOUR_CONSUMER_SECRET>|TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}|g" docker-compose.yml
